site_name: API del Servicio de Normalización de Datos Geográficos de Argentina
site_url: http://apis.datos.gob.ar/georef/
site_description: Documentación de la API del Servicio de Normalización de Datos Geográficos de la República Argentina
site_author: Datos Argentina

repo_url: https://github.com/datosgobar/georef-ar-api
edit_uri: ""

nav:
  - Inicio: index.md
  - Usuarios:
    - Ejemplos de uso: quick_start.md
    - Usar en planillas de cálculo: spreadsheet_integration.md
    - Usar en Python: python_usage.md
    - Autenticarse con JWT: jwt-token.md
    - Referencia API: https://datosgobar.github.io/georef-ar-api/
  - Aplicaciones: applications.md
  - Desarrolladores:
    - Ambiente de desarrollo y deploy: developers/georef-api-development.md
    - Instalación de Python 3.6: developers/python3.6.md
    - Proceso de ETL y Datos: developers/georef-api-data.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
      - yaml
      - django
      - python

extra_css:
  - css/extra.css

plugins:
  - search:
      lang: es

markdown_extensions:
  - toc:
      permalink: True
  - attr_list
  - fenced_code
  - sane_lists
